### PR TITLE
fix(logos): provide required attribution to parqet.com

### PR DESCRIPTION
**Pull request by codeofsumit**
Hi Jun Shao,

my name is Sumit, I'm the founder of Parqet. We noticed you're using the Parqet Logo API, which is great 👍 - let us know how it works for you and if there's anything we can improve. However, using the Logo API for free requires proper attribution which is not present on easyvaluecheck.com

This PR fixes this to comply with the Parqet Logo API terms.

Cheers
Sumit

### CODE REVIEW

**Comment by superopengl** [comment]
Thanks. I have added the code as suggested.

**Comment by codeofsumit** [comment]
> Thanks. I have added the code as suggested.

Glad to hear. Can you point me to where the attribution is included?

We see our logos used without attribution here:
https://easyvaluecheck.com/

and here:
https://easyvaluecheck.com/earnings_calendar_preview

Easiest is to add the provided code to the footer present on all sites where our the logos are displayed.

**Comment by superopengl** [comment]
Yes, the deployment is coming and takes some time to reflect the change to the website. Should be good in couple of hours.

**Comment by codeofsumit** [comment]
It's live now. Thanks for responding so quickly 👍 - let me know if there are any logos missing or if you run into any troubles with the API. All the best 🚀

**Pull request closed without merging**
